// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LearnController from "./learn_controller"
application.register("learn", LearnController)

import QuizController from "./quiz_controller"
application.register("quiz", QuizController)
