default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greatstudier_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: greatstudier_test

production:
  <<: *default
  database: greatstudier_production
  host: localhost
  username: greatstudier
  password: <%= ENV["GREAT_STUDIER_DATABASE_PASSWORD"] %>
